title: somecollagist
author:
  name: Johann Scott
  email: johann@somecollagist.com

description: >-
  Johann's Blog and Portfolio
baseurl: ""
url: "https://somecollagist.github.io"

# # Build settings
# plugins:
  # - jekyll-feed
sass:
  sass_dir: _sass

# Config for GitHub Pages
lsi: false
safe: true
source: .
incremental: false
highlighter: rouge
gist:
  noscript: false
kramdown:
  math_engine: mathjax
  syntax_highlighter: rouge